"""Deterministic renderer for identity-only Stellar AI archetype triggers."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Iterable

try:
    from tools.stellar_ai_nation_model import (
        ARCHETYPE_PRECEDENCE,
        OUTSIDE_PRIMARY_PERSONALITIES,
        PEGASUS_444_PERSONALITY_SHA256,
        PRIMARY_PERSONALITY_GROUPS,
        REVIEWED_444_PERSONALITY_IDS,
        Archetype,
    )
except ModuleNotFoundError:
    from stellar_ai_nation_model import (  # type: ignore[no-redef]
        ARCHETYPE_PRECEDENCE,
        OUTSIDE_PRIMARY_PERSONALITIES,
        PEGASUS_444_PERSONALITY_SHA256,
        PRIMARY_PERSONALITY_GROUPS,
        REVIEWED_444_PERSONALITY_IDS,
        Archetype,
    )


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def render_archetype_triggers(personality_path: Path) -> str:
    """Render mutually exclusive country-identity triggers with no policy effects."""

    primary_archetypes = tuple(
        archetype
        for archetype in ARCHETYPE_PRECEDENCE
        if archetype is not Archetype.BALANCED
    )
    if tuple(PRIMARY_PERSONALITY_GROUPS) != primary_archetypes:
        raise RuntimeError(
            "nation-model personality groups are not in archetype precedence order"
        )

    grouped_personalities = tuple(
        personality_id
        for archetype in primary_archetypes
        for personality_id in PRIMARY_PERSONALITY_GROUPS[archetype]
    )
    if len(grouped_personalities) != len(set(grouped_personalities)):
        raise RuntimeError(
            "a personality appears in more than one primary archetype group"
        )
    if (set(grouped_personalities) | set(OUTSIDE_PRIMARY_PERSONALITIES)) != set(
        REVIEWED_444_PERSONALITY_IDS
    ):
        raise RuntimeError(
            "reviewed personality coverage is inconsistent with the nation model"
        )

    if not personality_path.is_file():
        raise FileNotFoundError(
            f"missing pinned personality source: {personality_path}"
        )
    actual_hash = _file_sha256(personality_path)
    if actual_hash != PEGASUS_444_PERSONALITY_SHA256:
        raise RuntimeError(
            "Pegasus 4.4.4 personality source drift: "
            f"expected {PEGASUS_444_PERSONALITY_SHA256}, got {actual_hash}"
        )
    source_text = personality_path.read_text(encoding="utf-8-sig")
    source_objects = set(
        re.findall(r"(?m)^([A-Za-z0-9_.~!@:+-]+)\s*=\s*\{", source_text)
    )
    missing_personalities = sorted(set(REVIEWED_444_PERSONALITY_IDS) - source_objects)
    if missing_personalities:
        raise RuntimeError(
            "reviewed personality IDs missing from pinned source: "
            + ", ".join(missing_personalities)
        )

    lines = [
        "# Generated by tools/generate_stellar_ai_archetype_triggers.py.",
        "# Also owned by tools/generate_stellar_ai_director_patch.py.",
        "# Pegasus 4.4.4 personality source SHA256:",
        f"# {PEGASUS_444_PERSONALITY_SHA256}",
        "# Identity classification only: no weights, resources, state, or orders.",
        "",
    ]

    def add_trigger(name: str, body: Iterable[str]) -> None:
        lines.append(f"{name} = {{")
        lines.extend(f"\t{line}" if line else "" for line in body)
        lines.extend(("}", ""))

    def or_lines(assignments: Iterable[str]) -> list[str]:
        return ["OR = {"] + [f"\t{assignment}" for assignment in assignments] + ["}"]

    def nor_lines(assignments: Iterable[str]) -> list[str]:
        return ["NOR = {"] + [f"\t{assignment}" for assignment in assignments] + ["}"]

    def hard_name(archetype: Archetype) -> str:
        return f"staid_archetype_hard_{archetype.value}"

    def candidate_name(archetype: Archetype) -> str:
        return f"staid_archetype_candidate_{archetype.value}"

    add_trigger(
        "staid_archetype_eligible_country",
        ("is_country_type = default", "is_nomadic = no"),
    )

    hard_extras = {
        Archetype.EXTERMINATION: (
            "has_valid_civic = civic_fanatic_purifiers",
            "has_valid_civic = civic_hive_devouring_swarm",
            "has_valid_civic = civic_machine_terminator",
            "has_valid_civic = civic_scorched_earth",
            "has_valid_civic = civic_hive_scorched_earth",
            "has_ascension_perk = ap_become_the_crisis",
        ),
        Archetype.DEFENSIVE: (
            "has_ethic = ethic_fanatic_pacifist",
            "has_valid_civic = civic_inwards_perfection",
        ),
    }
    for archetype in primary_archetypes:
        identity_assignments = [
            f"has_ai_personality = {personality_id}"
            for personality_id in PRIMARY_PERSONALITY_GROUPS[archetype]
        ]
        identity_assignments.extend(hard_extras.get(archetype, ()))
        add_trigger(hard_name(archetype), or_lines(identity_assignments))

    conflict_pairs: list[str] = ["OR = {"]
    for index, left in enumerate(primary_archetypes):
        for right in primary_archetypes[index + 1 :]:
            conflict_pairs.extend(
                (
                    "\tAND = {",
                    f"\t\t{hard_name(left)} = yes",
                    f"\t\t{hard_name(right)} = yes",
                    "\t}",
                )
            )
    conflict_pairs.append("}")
    add_trigger("staid_archetype_identity_conflict", conflict_pairs)

    add_trigger(
        candidate_name(Archetype.EXTERMINATION),
        [
            "OR = {",
            f"\t{hard_name(Archetype.EXTERMINATION)} = yes",
            "\tAND = {",
            *[
                f"\t\t{line}"
                for line in nor_lines(
                    f"{hard_name(archetype)} = yes"
                    for archetype in primary_archetypes[1:]
                )
            ],
            "\t\tOR = {",
            "\t\t\thas_ai_personality_behaviour = purger",
            "\t\t\thas_ai_personality_behaviour = attack_neutrals",
            "\t\t}",
            "\t}",
            "}",
        ],
    )
    add_trigger(
        candidate_name(Archetype.GESTALT_GROWTH),
        [
            "OR = {",
            f"\t{hard_name(Archetype.GESTALT_GROWTH)} = yes",
            "\tAND = {",
            *[
                f"\t\t{line}"
                for line in nor_lines(
                    f"{hard_name(archetype)} = yes"
                    for archetype in primary_archetypes[2:]
                )
            ],
            "\t\tOR = {",
            "\t\t\tis_hive_empire = yes",
            "\t\t\tis_machine_empire = yes",
            "\t\t\tis_wilderness_empire = yes",
            "\t\t}",
            "\t}",
            "}",
        ],
    )
    add_trigger(
        candidate_name(Archetype.DEFENSIVE),
        [
            "OR = {",
            f"\t{hard_name(Archetype.DEFENSIVE)} = yes",
            "\tAND = {",
            *[
                f"\t\t{line}"
                for line in nor_lines(
                    f"{hard_name(archetype)} = yes"
                    for archetype in primary_archetypes[3:]
                )
            ],
            "\t\thas_federator_personality = no",
            "\t\tOR = {",
            "\t\t\thas_ai_personality_behaviour = isolationist",
            "\t\t\tis_pacifist = yes",
            "\t\t}",
            "\t}",
            "}",
        ],
    )
    add_trigger(
        candidate_name(Archetype.RESEARCH),
        [
            "OR = {",
            f"\t{hard_name(Archetype.RESEARCH)} = yes",
            "\tAND = {",
            *[
                f"\t\t{line}"
                for line in nor_lines(
                    f"{hard_name(archetype)} = yes"
                    for archetype in primary_archetypes[4:]
                )
            ],
            "\t\thas_federator_personality = no",
            "\t\tNOR = {",
            "\t\t\thas_ai_personality_behaviour = conqueror",
            "\t\t\thas_ai_personality_behaviour = subjugator",
            "\t\t\thas_ai_personality_behaviour = dominator",
            "\t\t}",
            "\t\tOR = {",
            "\t\t\thas_valid_civic = civic_technocracy",
            "\t\t\thas_ethic = ethic_materialist",
            "\t\t\thas_ethic = ethic_fanatic_materialist",
            "\t\t}",
            "\t}",
            "}",
        ],
    )
    add_trigger(
        candidate_name(Archetype.DIPLOMATIC),
        [
            "OR = {",
            f"\t{hard_name(Archetype.DIPLOMATIC)} = yes",
            "\tAND = {",
            f"\t\t{hard_name(Archetype.CONQUEST)} = no",
            "\t\tNOR = {",
            "\t\t\thas_ai_personality_behaviour = conqueror",
            "\t\t}",
            "\t\tOR = {",
            "\t\t\thas_federator_personality = yes",
            "\t\t\thas_ai_personality_behaviour = liberator",
            "\t\t\thas_ai_personality_behaviour = multispecies",
            "\t\t\thas_ai_personality_behaviour = uplifter",
            "\t\t\thas_ethic = ethic_xenophile",
            "\t\t\thas_ethic = ethic_fanatic_xenophile",
            "\t\t\thas_ethic = ethic_egalitarian",
            "\t\t\thas_ethic = ethic_fanatic_egalitarian",
            "\t\t}",
            "\t}",
            "}",
        ],
    )
    add_trigger(
        candidate_name(Archetype.CONQUEST),
        [
            "OR = {",
            f"\t{hard_name(Archetype.CONQUEST)} = yes",
            "\thas_ai_personality_behaviour = conqueror",
            "\thas_ai_personality_behaviour = subjugator",
            "\thas_ai_personality_behaviour = dominator",
            "\thas_ai_personality_behaviour = propagator",
            "\thas_ethic = ethic_militarist",
            "\thas_ethic = ethic_fanatic_militarist",
            "\thas_valid_civic = civic_distinguished_admiralty",
            "\thas_valid_civic = civic_nationalistic_zeal",
            "\thas_valid_civic = civic_barbaric_despoilers",
            "\thas_valid_civic = civic_machine_assimilator",
            "}",
        ],
    )

    preceding_candidates: list[str] = []
    for archetype in primary_archetypes:
        body = [
            "staid_archetype_eligible_country = yes",
            "staid_archetype_identity_conflict = no",
        ]
        if preceding_candidates:
            body.extend(nor_lines(f"{name} = yes" for name in preceding_candidates))
        body.append(f"{candidate_name(archetype)} = yes")
        add_trigger(f"staid_archetype_{archetype.value}", body)
        preceding_candidates.append(candidate_name(archetype))

    add_trigger(
        "staid_archetype_balanced",
        [
            "staid_archetype_eligible_country = yes",
            *nor_lines(
                f"staid_archetype_{archetype.value} = yes"
                for archetype in primary_archetypes
            ),
        ],
    )

    return "\n".join(lines).rstrip() + "\n"
